[versions]
agp = "8.2.2"
kotlin = "1.9.22"
coreKtx = "1.12.0"
lifecycleRuntimeKtx = "2.7.0"
activityCompose = "1.8.2"
composeBom = "2023.10.01"
lifecycleViewModel = "2.7.0"

[libraries]
androidx.core.ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx.lifecycle.runtime.ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx.activity.compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx.compose.bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx.compose.ui = { group = "androidx.compose.ui", name = "ui" }
androidx.compose.ui.graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx.compose.ui.tooling.preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx.compose.material3 = { group = "androidx.compose.material3", name = "material3" }
androidx.lifecycle.viewmodel.compose = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "lifecycleViewModel" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }